### ISSUE TITLE
Remove unused modules out of `server.js`

### ISSUE THREAD

**Issue by yvonne-liu** [FAC-11/littleFACtautocomplete-week4#36]
![screen shot 2017-07-21 at 10 11 33 am](https://user-images.githubusercontent.com/22013117/28457177-05f9c398-6dfd-11e7-9a02-f9b55abd47dc.png)

We're not using `path` or `fs` in `server.js` 😊

**Comment by azayneeva** [comment]
Thank you, @yvonne-liu :) indeed we don't need them there! got rid of them
