### ISSUE TITLE
Possible css for hover over list elements

### ISSUE THREAD

**Issue by mineshmshah** [FAC-11/littleFACtautocomplete-week4#48]
When the list elements appear it is unclear that you need to click on them. An easy fix is to add a hover property to the css list elements like the following with some highlight :

li hover: {
...
}

not a necessity but a little suggestion to make it clear :)

**Comment by yvonne-liu** [comment]
Relates to #41 😉

**Comment by bowssy88** [comment]
thanks guys , a cursor to a finger and a border thickness has been added to fix this
